### ISSUE TITLE
Autolist for plugins

### ISSUE THREAD

**Issue by ai** [mxstbr/postcss.parts#1]
You can extract plugins automatically by `postcss-plugin` keyword

**Comment by mxstbr** [comment]
From where? I scraped the PostCSS README with python, but even after that the information needed some manual correction. Any pointers?

**Comment by MoOx** [comment]
https://www.npmjs.com/search?q=postcss-plugin

**Comment by himynameisdave** [comment]
I am going try to rigorously maintain [this package](https://github.com/himynameisdave/postcss-plugins) which is literally just a `require`able list of postcss plugins, currently sourced from the list on the [PostCSS readme](https://github.com/postcss/postcss#readme).

Currently working on a PR to show you how that package could work with this app :smile:

**Comment by mxstbr** [comment]
Done with 6bb583846f027c4f06301a361090290bb523226d
