### ISSUE TITLE
update postcss-plugins automagically

### ISSUE THREAD

**Issue by himynameisdave** [mxstbr/postcss.parts#10]
The [`postcss-plugins`](https://github.com/himynameisdave/postcss-plugins) module is constantly being updated, and I feel like the live version is only updated manually when someone re-uploads the `/node_modules` folder. 

The reason I bring this up is that I added a plugin today and I haven't seen the changes reflected live on the site.

**Comment by mxstbr** [comment]
You are very correct. The bundle.js on the server is now out of date, and I have to rebuild the app to reflect the changes. That's just the way npm modules work though, and nothing one can fix.

EDIT: You also have to publish the new version of postcss-plugins to npm for me to get the changes.

**Comment by mxstbr** [comment]
Sorry, close the issue on accident. 

I think the way to go here is to HTTP GET the plugins.json file in the postcss-plugins repo, i.e. `GET https://raw.githubusercontent.com/himynameisdave/postcss-plugins/master/plugins.json` That way it would always be up to date. We can still fallback on the cached version by the module if somehow GitHub is down. If that looks good to you I'll go ahead and implement that!

**Comment by himynameisdave** [comment]
My thoughts exactly :smile: 
So on initial load, just load up those modules in the `bundle.js`, and then go fire off that `GET` which will update the data if need be. Then what? Cache the updated bundle in localStorage? Send you a notification to update?

**Comment by mxstbr** [comment]
No, just do it client side everytime and update silently. We could cache it though, that's not a bad idea!
