### ISSUE TITLE
Provide Accessibility/Usablity

### ISSUE THREAD

**Issue by anselmh** [mxstbr/postcss.parts#13]
- [x] Add URIs / hashes for specific search "results"
- [x] Make links real links so they can be opened in new tabs (related to the first task)
- [x] Consider `autofocus` on the search form field
- [x] Add a clear search term button when something has been entered
- [x] Add proper `:focus` styles and make the interface "tab-able"

**Comment by browniefed** [comment]
The first 2 should be a things now. Need to probably switch to hash routing if we can pass through to the `index.html` always.

**Comment by browniefed** [comment]
Did the rest of these things with https://github.com/mxstbr/postcss.parts/pull/20
Also confirmed that tabbing w/ everything being links works just fine, and adds appropriate outlines  on focus, no need for custom :focus stuff unless we care.

**Comment by mxstbr** [comment]
Awesome, thanks @browniefed!
