### ISSUE TITLE
404 Tag

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/postcss.parts#16]
Right now, when going to http://postcss.parts/tag/doesnt-exist it doesn't show that the tag doesn't exist – which it should!

**Comment by browniefed** [comment]
Woops, I'll get to that tonight

**Comment by browniefed** [comment]
#17 should close this out.

**Comment by browniefed** [comment]
Fixed

**Comment by mxstbr** [comment]
Thanks so much for the help @browniefed!
