### ISSUE TITLE
Speed up script compilation

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/postcss.parts#4]
Currently, Browserify compiles the JS files into js/bundle.js, and uglify then mini— and uglifies the js/bundle.js file into js/bundle.min.js. While this is preferable for production, it takes way too long for development. Maybe skip uglify for development?

**Comment by himynameisdave** [comment]
Yes please because it makes it harder to debug!

**Comment by browniefed** [comment]
I can tackle this later, just probably switch over to webpack and hot reloading goodness for absolutely no reason :)

**Comment by browniefed** [comment]
Unless we prefer browserify for some reason, but grunt seems entirely unnecessary here.

**Comment by mxstbr** [comment]
Yes please webpack, back when I wrote this I had no idea what I was doing!

**Comment by browniefed** [comment]
#18 should resolve this.

**Comment by browniefed** [comment]
Didn't go with hot reloading since I converted all of the components to stateless components so it wouldn't have worked `¯\_(ツ)_/¯`

**Comment by browniefed** [comment]
It's landed
